%% build_architecture.m — GENERATED from SysML v2 (rover_a1) by
%% .claude/skills/system_composer_sysml/scripts/sysml_to_syscomp.py. Do not edit; re-generate.
%% Builds <name>Arch.slx + <name>Interfaces.sldd + RoverProfile.xml + <name>Alloc.mldatx in ./arch
function build_architecture()
here = fileparts(mfilename('fullpath')); out = fullfile(here, 'arch');
if ~isfolder(out), mkdir(out); end
old = cd(out); cleanup = onCleanup(@() cd(old));
mdl = "RoverA1Arch"; dd = "RoverA1Interfaces.sldd"; prof = "RoverProfile"; aset = "RoverA1Alloc";
% --- idempotent: close + delete previous artifacts without dialogs
if bdIsLoaded(mdl), close_system(mdl, 0); end
systemcomposer.allocation.AllocationSet.closeAll; systemcomposer.profile.Profile.closeAll;
Simulink.data.dictionary.closeAll('-discard');
for f = [mdl + ".slx", dd, prof + ".xml", aset + ".mldatx"], if isfile(f), delete(f); end, end

model = systemcomposer.createModel(mdl); arch = model.Architecture;
% --- interfaces (item defs)
dict = systemcomposer.createDictionary(dd); I = struct();
I.BatteryStatus = addInterface(dict, "BatteryStatus");
addElement(I.BatteryStatus, "stateOfCharge", Type="double", Units="");
addElement(I.BatteryStatus, "temperature", Type="double", Units="K");
I.CrsfFrame = addInterface(dict, "CrsfFrame");
I.ElectricPower = addInterface(dict, "ElectricPower");
I.Imu = addInterface(dict, "Imu");
I.LaserScan = addInterface(dict, "LaserScan");
I.ModbusFrame = addInterface(dict, "ModbusFrame");
I.NavSatFix = addInterface(dict, "NavSatFix");
addElement(I.NavSatFix, "horizontalStd", Type="double", Units="m");
I.Odometry = addInterface(dict, "Odometry");
addElement(I.Odometry, "x", Type="double", Units="m");
addElement(I.Odometry, "y", Type="double", Units="m");
addElement(I.Odometry, "yaw", Type="double", Units="rad");
I.PointCloud2 = addInterface(dict, "PointCloud2");
I.TwistStamped = addInterface(dict, "TwistStamped");
addElement(I.TwistStamped, "linearX", Type="double", Units="m/s");
addElement(I.TwistStamped, "angularZ", Type="double", Units="rad/s");
I.WheelVelocityCommand = addInterface(dict, "WheelVelocityCommand");
addElement(I.WheelVelocityCommand, "wheelSpeed", Type="double", Units="rad/s");
linkDictionary(model, dd);
% --- profile: RosTopic stereotype for connectors
profile = systemcomposer.profile.Profile.createProfile(prof);
st = addStereotype(profile, "RosTopic", AppliesTo="Connector");
addProperty(st, "topic", Type="string"); addProperty(st, "msgType", Type="string"); addProperty(st, "qos", Type="string");
save(profile); applyProfile(model, prof);

% --- components, ports, parameters
addParameter(arch, "bodyMass", Value="33.45", Units="kg");
addParameter(arch, "wheelSeparation", Value="0.62602", Units="m");
addParameter(arch, "wheelbase", Value="0.5084", Units="m");
addParameter(arch, "averageLoad", Value="160", Units="W");
c_drive_1 = addComponent(arch, "drive_1");
c_drive_1_wheel = addComponent(c_drive_1.Architecture, "wheel");
addParameter(c_drive_1_wheel.Architecture, "radius", Value="0.1651", Units="m");
addParameter(c_drive_1_wheel.Architecture, "width", Value="0.108", Units="m");
addParameter(c_drive_1_wheel.Architecture, "mass", Value="2.5", Units="kg");
c_drive_1_motor = addComponent(c_drive_1.Architecture, "motor");
addParameter(c_drive_1_motor.Architecture, "noLoadSpeed", Value="293.2", Units="rad/s");
addParameter(c_drive_1_motor.Architecture, "gearRatio", Value="23.3", Units="");
addParameter(c_drive_1_motor.Architecture, "gearboxEfficiency", Value="0.70", Units="");
addParameter(c_drive_1_motor.Architecture, "currentLimit", Value="15", Units="A");
addParameter(c_drive_1_motor.Architecture, "jointVelocityLimit", Value="10.958", Units="rad/s");
c_drive_1_controller = addComponent(c_drive_1.Architecture, "controller");
p = addPort(c_drive_1_controller.Architecture, "wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_drive_1_controller.Architecture, "powerIn", "in"); setInterface(p, I.ElectricPower);
c_drive_2 = addComponent(arch, "drive_2");
c_drive_2_wheel = addComponent(c_drive_2.Architecture, "wheel");
addParameter(c_drive_2_wheel.Architecture, "radius", Value="0.1651", Units="m");
addParameter(c_drive_2_wheel.Architecture, "width", Value="0.108", Units="m");
addParameter(c_drive_2_wheel.Architecture, "mass", Value="2.5", Units="kg");
c_drive_2_motor = addComponent(c_drive_2.Architecture, "motor");
addParameter(c_drive_2_motor.Architecture, "noLoadSpeed", Value="293.2", Units="rad/s");
addParameter(c_drive_2_motor.Architecture, "gearRatio", Value="23.3", Units="");
addParameter(c_drive_2_motor.Architecture, "gearboxEfficiency", Value="0.70", Units="");
addParameter(c_drive_2_motor.Architecture, "currentLimit", Value="15", Units="A");
addParameter(c_drive_2_motor.Architecture, "jointVelocityLimit", Value="10.958", Units="rad/s");
c_drive_2_controller = addComponent(c_drive_2.Architecture, "controller");
p = addPort(c_drive_2_controller.Architecture, "wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_drive_2_controller.Architecture, "powerIn", "in"); setInterface(p, I.ElectricPower);
c_drive_3 = addComponent(arch, "drive_3");
c_drive_3_wheel = addComponent(c_drive_3.Architecture, "wheel");
addParameter(c_drive_3_wheel.Architecture, "radius", Value="0.1651", Units="m");
addParameter(c_drive_3_wheel.Architecture, "width", Value="0.108", Units="m");
addParameter(c_drive_3_wheel.Architecture, "mass", Value="2.5", Units="kg");
c_drive_3_motor = addComponent(c_drive_3.Architecture, "motor");
addParameter(c_drive_3_motor.Architecture, "noLoadSpeed", Value="293.2", Units="rad/s");
addParameter(c_drive_3_motor.Architecture, "gearRatio", Value="23.3", Units="");
addParameter(c_drive_3_motor.Architecture, "gearboxEfficiency", Value="0.70", Units="");
addParameter(c_drive_3_motor.Architecture, "currentLimit", Value="15", Units="A");
addParameter(c_drive_3_motor.Architecture, "jointVelocityLimit", Value="10.958", Units="rad/s");
c_drive_3_controller = addComponent(c_drive_3.Architecture, "controller");
p = addPort(c_drive_3_controller.Architecture, "wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_drive_3_controller.Architecture, "powerIn", "in"); setInterface(p, I.ElectricPower);
c_drive_4 = addComponent(arch, "drive_4");
c_drive_4_wheel = addComponent(c_drive_4.Architecture, "wheel");
addParameter(c_drive_4_wheel.Architecture, "radius", Value="0.1651", Units="m");
addParameter(c_drive_4_wheel.Architecture, "width", Value="0.108", Units="m");
addParameter(c_drive_4_wheel.Architecture, "mass", Value="2.5", Units="kg");
c_drive_4_motor = addComponent(c_drive_4.Architecture, "motor");
addParameter(c_drive_4_motor.Architecture, "noLoadSpeed", Value="293.2", Units="rad/s");
addParameter(c_drive_4_motor.Architecture, "gearRatio", Value="23.3", Units="");
addParameter(c_drive_4_motor.Architecture, "gearboxEfficiency", Value="0.70", Units="");
addParameter(c_drive_4_motor.Architecture, "currentLimit", Value="15", Units="A");
addParameter(c_drive_4_motor.Architecture, "jointVelocityLimit", Value="10.958", Units="rad/s");
c_drive_4_controller = addComponent(c_drive_4.Architecture, "controller");
p = addPort(c_drive_4_controller.Architecture, "wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_drive_4_controller.Architecture, "powerIn", "in"); setInterface(p, I.ElectricPower);
c_battery = addComponent(arch, "battery");
p = addPort(c_battery.Architecture, "powerOut", "out"); setInterface(p, I.ElectricPower);
p = addPort(c_battery.Architecture, "statusOut", "out"); setInterface(p, I.BatteryStatus);
addParameter(c_battery.Architecture, "capacity", Value="40", Units="A*h");
addParameter(c_battery.Architecture, "nominalVoltage", Value="24", Units="V");
c_safetyController = addComponent(arch, "safetyController");
p = addPort(c_safetyController.Architecture, "modbus", "in"); setInterface(p, I.ModbusFrame);
addParameter(c_safetyController.Architecture, "watchdogPeriod", Value="0.2", Units="s");
c_compute = addComponent(arch, "compute");
p = addPort(c_compute.Architecture, "modbus", "out"); setInterface(p, I.ModbusFrame);
p = addPort(c_compute.Architecture, "wheelCmdOut_1", "out"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_compute.Architecture, "wheelCmdOut_2", "out"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_compute.Architecture, "wheelCmdOut_3", "out"); setInterface(p, I.WheelVelocityCommand);
p = addPort(c_compute.Architecture, "wheelCmdOut_4", "out"); setInterface(p, I.WheelVelocityCommand);
c_lidar = addComponent(arch, "lidar");
p = addPort(c_lidar.Architecture, "cloudOut", "out"); setInterface(p, I.PointCloud2);
addParameter(c_lidar.Architecture, "scanRate", Value="10", Units="Hz");
c_imu = addComponent(arch, "imu");
p = addPort(c_imu.Architecture, "imuOut", "out"); setInterface(p, I.Imu);
c_gnss = addComponent(arch, "gnss");
p = addPort(c_gnss.Architecture, "fixOut", "out"); setInterface(p, I.NavSatFix);
addParameter(c_gnss.Architecture, "fixRate", Value="1", Units="Hz");
c_rc = addComponent(arch, "rc");
p = addPort(c_rc.Architecture, "crsfOut", "out"); setInterface(p, I.CrsfFrame);
c_platform = addComponent(arch, "platform");
c_platform_twistMux = addComponent(c_platform.Architecture, "twistMux");
p = addPort(c_platform_twistMux.Architecture, "webIn", "in"); setInterface(p, I.TwistStamped);
p = addPort(c_platform_twistMux.Architecture, "rcIn", "in"); setInterface(p, I.TwistStamped);
p = addPort(c_platform_twistMux.Architecture, "navIn", "in"); setInterface(p, I.TwistStamped);
p = addPort(c_platform_twistMux.Architecture, "cmdOut", "out"); setInterface(p, I.TwistStamped);
addParameter(c_platform_twistMux.Architecture, "inputTimeout", Value="0.5", Units="s");
c_platform_driveController = addComponent(c_platform.Architecture, "driveController");
p = addPort(c_platform_driveController.Architecture, "cmdIn", "in"); setInterface(p, I.TwistStamped);
p = addPort(c_platform_driveController.Architecture, "odomOut", "out"); setInterface(p, I.Odometry);
addParameter(c_platform_driveController.Architecture, "updateRate", Value="100", Units="Hz");
addParameter(c_platform_driveController.Architecture, "maxLinearSpeed", Value="1.2", Units="m/s");
addParameter(c_platform_driveController.Architecture, "maxLinearAccel", Value="2.7", Units="m/s^2");
addParameter(c_platform_driveController.Architecture, "maxAngularSpeed", Value="1.0", Units="rad/s");
addParameter(c_platform_driveController.Architecture, "cmdTimeout", Value="0.5", Units="s");
c_platform_localization = addComponent(c_platform.Architecture, "localization");
p = addPort(c_platform_localization.Architecture, "wheelOdomIn", "in"); setInterface(p, I.Odometry);
p = addPort(c_platform_localization.Architecture, "imuIn", "in"); setInterface(p, I.Imu);
p = addPort(c_platform_localization.Architecture, "fixIn", "in"); setInterface(p, I.NavSatFix);
p = addPort(c_platform_localization.Architecture, "odomOut", "out"); setInterface(p, I.Odometry);
addParameter(c_platform_localization.Architecture, "ekfRate", Value="50", Units="Hz");
c_platform_crsfTeleop = addComponent(c_platform.Architecture, "crsfTeleop");
p = addPort(c_platform_crsfTeleop.Architecture, "crsfIn", "in"); setInterface(p, I.CrsfFrame);
p = addPort(c_platform_crsfTeleop.Architecture, "cmdOut", "out"); setInterface(p, I.TwistStamped);
c_platform_safetyManager = addComponent(c_platform.Architecture, "safetyManager");
p = addPort(c_platform_safetyManager.Architecture, "batteryIn", "in"); setInterface(p, I.BatteryStatus);
p = addPort(c_platform_safetyManager.Architecture, "modbus", "out"); setInterface(p, I.ModbusFrame);
addParameter(c_platform_safetyManager.Architecture, "batteryEstopTemperature", Value="323.15", Units="K");
addParameter(c_platform_safetyManager.Architecture, "batteryShutdownTemperature", Value="333.15", Units="K");
c_platform_batteryMonitor = addComponent(c_platform.Architecture, "batteryMonitor");
p = addPort(c_platform_batteryMonitor.Architecture, "bmsIn", "in"); setInterface(p, I.BatteryStatus);
p = addPort(c_platform_batteryMonitor.Architecture, "statusOut", "out"); setInterface(p, I.BatteryStatus);
c_orchestrator = addComponent(arch, "orchestrator");
c_orchestrator_navigation = addComponent(c_orchestrator.Architecture, "navigation");
p = addPort(c_orchestrator_navigation.Architecture, "odomIn", "in"); setInterface(p, I.Odometry);
p = addPort(c_orchestrator_navigation.Architecture, "scanIn", "in"); setInterface(p, I.LaserScan);
p = addPort(c_orchestrator_navigation.Architecture, "cmdOut", "out"); setInterface(p, I.TwistStamped);
addParameter(c_orchestrator_navigation.Architecture, "maxForwardSpeed", Value="0.8", Units="m/s");
addParameter(c_orchestrator_navigation.Architecture, "maxReverseSpeed", Value="0.5", Units="m/s");
addParameter(c_orchestrator_navigation.Architecture, "footprintRadius", Value="0.693", Units="m");
c_sensors = addComponent(arch, "sensors");
c_sensors_scanProjection = addComponent(c_sensors.Architecture, "scanProjection");
p = addPort(c_sensors_scanProjection.Architecture, "cloudIn", "in"); setInterface(p, I.PointCloud2);
p = addPort(c_sensors_scanProjection.Architecture, "scanOut", "out"); setInterface(p, I.LaserScan);
c_driveInterface = addComponent(arch, "driveInterface");
c_driveInterface_driveUi = addComponent(c_driveInterface.Architecture, "driveUi");
p = addPort(c_driveInterface_driveUi.Architecture, "cmdOut", "out"); setInterface(p, I.TwistStamped);
p = addPort(c_driveInterface_driveUi.Architecture, "batteryIn", "in"); setInterface(p, I.BatteryStatus);

% --- connectors (flows + interface links), routed through parent boundary ports
C = {};
p = addPort(c_driveInterface.Architecture, "driveUi_cmdOut", "out"); setInterface(p, I.TwistStamped);
connect(getPort(c_driveInterface_driveUi, "cmdOut"), getPort(c_driveInterface.Architecture, "driveUi_cmdOut"));
p = addPort(c_platform.Architecture, "twistMux_webIn", "in"); setInterface(p, I.TwistStamped);
connect(getPort(c_platform.Architecture, "twistMux_webIn"), getPort(c_platform_twistMux, "webIn"));
C{end+1} = connect(getPort(c_driveInterface, "driveUi_cmdOut"), getPort(c_platform, "twistMux_webIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"teleop_foxglove_cmd_vel_stamped"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"geometry_msgs/TwistStamped"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
C{end+1} = connect(getPort(c_platform_crsfTeleop, "cmdOut"), getPort(c_platform_twistMux, "rcIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"teleop_elrs_cmd_vel_stamped"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"geometry_msgs/TwistStamped"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
p = addPort(c_orchestrator.Architecture, "navigation_cmdOut", "out"); setInterface(p, I.TwistStamped);
connect(getPort(c_orchestrator_navigation, "cmdOut"), getPort(c_orchestrator.Architecture, "navigation_cmdOut"));
p = addPort(c_platform.Architecture, "twistMux_navIn", "in"); setInterface(p, I.TwistStamped);
connect(getPort(c_platform.Architecture, "twistMux_navIn"), getPort(c_platform_twistMux, "navIn"));
C{end+1} = connect(getPort(c_orchestrator, "navigation_cmdOut"), getPort(c_platform, "twistMux_navIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"nav_cmd_vel_stamped"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"geometry_msgs/TwistStamped"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
C{end+1} = connect(getPort(c_platform_twistMux, "cmdOut"), getPort(c_platform_driveController, "cmdIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"cmd_vel"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"geometry_msgs/TwistStamped"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
C{end+1} = connect(getPort(c_platform_driveController, "odomOut"), getPort(c_platform_localization, "wheelOdomIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"odometry/wheels"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"nav_msgs/Odometry"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
p = addPort(c_platform.Architecture, "localization_imuIn", "in"); setInterface(p, I.Imu);
connect(getPort(c_platform.Architecture, "localization_imuIn"), getPort(c_platform_localization, "imuIn"));
C{end+1} = connect(getPort(c_imu, "imuOut"), getPort(c_platform, "localization_imuIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"imu/data"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"sensor_msgs/Imu"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"SensorData"');
p = addPort(c_platform.Architecture, "localization_fixIn", "in"); setInterface(p, I.NavSatFix);
connect(getPort(c_platform.Architecture, "localization_fixIn"), getPort(c_platform_localization, "fixIn"));
C{end+1} = connect(getPort(c_gnss, "fixOut"), getPort(c_platform, "localization_fixIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"gps/fix"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"sensor_msgs/NavSatFix"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"SensorData"');
p = addPort(c_platform.Architecture, "localization_odomOut", "out"); setInterface(p, I.Odometry);
connect(getPort(c_platform_localization, "odomOut"), getPort(c_platform.Architecture, "localization_odomOut"));
p = addPort(c_orchestrator.Architecture, "navigation_odomIn", "in"); setInterface(p, I.Odometry);
connect(getPort(c_orchestrator.Architecture, "navigation_odomIn"), getPort(c_orchestrator_navigation, "odomIn"));
C{end+1} = connect(getPort(c_platform, "localization_odomOut"), getPort(c_orchestrator, "navigation_odomIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"odometry/filtered"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"nav_msgs/Odometry"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
p = addPort(c_sensors.Architecture, "scanProjection_cloudIn", "in"); setInterface(p, I.PointCloud2);
connect(getPort(c_sensors.Architecture, "scanProjection_cloudIn"), getPort(c_sensors_scanProjection, "cloudIn"));
C{end+1} = connect(getPort(c_lidar, "cloudOut"), getPort(c_sensors, "scanProjection_cloudIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"rslidar_points"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"sensor_msgs/PointCloud2"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"SensorData"');
p = addPort(c_sensors.Architecture, "scanProjection_scanOut", "out"); setInterface(p, I.LaserScan);
connect(getPort(c_sensors_scanProjection, "scanOut"), getPort(c_sensors.Architecture, "scanProjection_scanOut"));
p = addPort(c_orchestrator.Architecture, "navigation_scanIn", "in"); setInterface(p, I.LaserScan);
connect(getPort(c_orchestrator.Architecture, "navigation_scanIn"), getPort(c_orchestrator_navigation, "scanIn"));
C{end+1} = connect(getPort(c_sensors, "scanProjection_scanOut"), getPort(c_orchestrator, "navigation_scanIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"scan"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"sensor_msgs/LaserScan"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"SensorData"');
p = addPort(c_drive_1.Architecture, "controller_powerIn", "in"); setInterface(p, I.ElectricPower);
connect(getPort(c_drive_1.Architecture, "controller_powerIn"), getPort(c_drive_1_controller, "powerIn"));
C{end+1} = connect(getPort(c_battery, "powerOut"), getPort(c_drive_1, "controller_powerIn"));
p = addPort(c_drive_2.Architecture, "controller_powerIn", "in"); setInterface(p, I.ElectricPower);
connect(getPort(c_drive_2.Architecture, "controller_powerIn"), getPort(c_drive_2_controller, "powerIn"));
C{end+1} = connect(getPort(c_battery, "powerOut"), getPort(c_drive_2, "controller_powerIn"));
p = addPort(c_drive_3.Architecture, "controller_powerIn", "in"); setInterface(p, I.ElectricPower);
connect(getPort(c_drive_3.Architecture, "controller_powerIn"), getPort(c_drive_3_controller, "powerIn"));
C{end+1} = connect(getPort(c_battery, "powerOut"), getPort(c_drive_3, "controller_powerIn"));
p = addPort(c_drive_4.Architecture, "controller_powerIn", "in"); setInterface(p, I.ElectricPower);
connect(getPort(c_drive_4.Architecture, "controller_powerIn"), getPort(c_drive_4_controller, "powerIn"));
C{end+1} = connect(getPort(c_battery, "powerOut"), getPort(c_drive_4, "controller_powerIn"));
p = addPort(c_drive_1.Architecture, "controller_wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
connect(getPort(c_drive_1.Architecture, "controller_wheelCmdIn"), getPort(c_drive_1_controller, "wheelCmdIn"));
C{end+1} = connect(getPort(c_compute, "wheelCmdOut_1"), getPort(c_drive_1, "controller_wheelCmdIn"));
p = addPort(c_drive_2.Architecture, "controller_wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
connect(getPort(c_drive_2.Architecture, "controller_wheelCmdIn"), getPort(c_drive_2_controller, "wheelCmdIn"));
C{end+1} = connect(getPort(c_compute, "wheelCmdOut_2"), getPort(c_drive_2, "controller_wheelCmdIn"));
p = addPort(c_drive_3.Architecture, "controller_wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
connect(getPort(c_drive_3.Architecture, "controller_wheelCmdIn"), getPort(c_drive_3_controller, "wheelCmdIn"));
C{end+1} = connect(getPort(c_compute, "wheelCmdOut_3"), getPort(c_drive_3, "controller_wheelCmdIn"));
p = addPort(c_drive_4.Architecture, "controller_wheelCmdIn", "in"); setInterface(p, I.WheelVelocityCommand);
connect(getPort(c_drive_4.Architecture, "controller_wheelCmdIn"), getPort(c_drive_4_controller, "wheelCmdIn"));
C{end+1} = connect(getPort(c_compute, "wheelCmdOut_4"), getPort(c_drive_4, "controller_wheelCmdIn"));
p = addPort(c_platform.Architecture, "crsfTeleop_crsfIn", "in"); setInterface(p, I.CrsfFrame);
connect(getPort(c_platform.Architecture, "crsfTeleop_crsfIn"), getPort(c_platform_crsfTeleop, "crsfIn"));
C{end+1} = connect(getPort(c_rc, "crsfOut"), getPort(c_platform, "crsfTeleop_crsfIn"));
p = addPort(c_platform.Architecture, "batteryMonitor_bmsIn", "in"); setInterface(p, I.BatteryStatus);
connect(getPort(c_platform.Architecture, "batteryMonitor_bmsIn"), getPort(c_platform_batteryMonitor, "bmsIn"));
C{end+1} = connect(getPort(c_battery, "statusOut"), getPort(c_platform, "batteryMonitor_bmsIn"));
C{end+1} = connect(getPort(c_platform_batteryMonitor, "statusOut"), getPort(c_platform_safetyManager, "batteryIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"rover_battery/battery_status"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"rover_msgs/BatteryStatus"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
p = addPort(c_platform.Architecture, "batteryMonitor_statusOut", "out"); setInterface(p, I.BatteryStatus);
connect(getPort(c_platform_batteryMonitor, "statusOut"), getPort(c_platform.Architecture, "batteryMonitor_statusOut"));
p = addPort(c_driveInterface.Architecture, "driveUi_batteryIn", "in"); setInterface(p, I.BatteryStatus);
connect(getPort(c_driveInterface.Architecture, "driveUi_batteryIn"), getPort(c_driveInterface_driveUi, "batteryIn"));
C{end+1} = connect(getPort(c_platform, "batteryMonitor_statusOut"), getPort(c_driveInterface, "driveUi_batteryIn"));
applyStereotype(C{end}, "RoverProfile.RosTopic");
setProperty(C{end}, "RoverProfile.RosTopic.topic", '"rover_battery/battery_status"');
setProperty(C{end}, "RoverProfile.RosTopic.msgType", '"rover_msgs/BatteryStatus"');
setProperty(C{end}, "RoverProfile.RosTopic.qos", '"Reliable"');
C{end+1} = connect(getPort(c_compute, "modbus"), getPort(c_safetyController, "modbus"));

% --- allocation (software services -> compute), same-model allocation set
as = systemcomposer.allocation.createAllocationSet(aset, mdl, mdl); sc = as.Scenarios(1);
allocate(sc, lookup(model, Path="RoverA1Arch/platform"), lookup(model, Path="RoverA1Arch/compute"));
allocate(sc, lookup(model, Path="RoverA1Arch/sensors"), lookup(model, Path="RoverA1Arch/compute"));
allocate(sc, lookup(model, Path="RoverA1Arch/driveInterface"), lookup(model, Path="RoverA1Arch/compute"));
allocate(sc, lookup(model, Path="RoverA1Arch/orchestrator"), lookup(model, Path="RoverA1Arch/compute"));

save(dict); save(model); save(as);
fprintf('Built %s: %d components, %d ports, %d parameters, %d connectors, %d allocations\n', ...
    mdl, 36, 43, 53, 46, 4);
end
